import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Textbook sidebar configuration for Physical AI & Humanoid Robotics.
 * Uses autogenerated sidebar from docs folder structure.
 * Each chapter folder has a _category_.json for ordering.
 */
const sidebars: SidebarsConfig = {
  textbookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
