openapi: 3.0.3
info:
  title: Book Authentication API
  description: Authentication endpoints for the AI-Native Textbook
  version: 1.0.0

servers:
  - url: https://safdarayubpk-2book-backend.hf.space
    description: Production (HuggingFace Spaces)
  - url: http://localhost:8000
    description: Local development

paths:
  /api/auth/sign-up:
    post:
      summary: Create new user account
      description: Register a new user with email, password, and background information
      operationId: signUp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        '201':
          description: Account created successfully
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Session cookie (httpOnly)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Email already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/sign-in:
    post:
      summary: Sign in existing user
      description: Authenticate with email and password
      operationId: signIn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        '200':
          description: Login successful
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Session cookie (httpOnly)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/session:
    get:
      summary: Get current session
      description: Returns current user if authenticated, null otherwise
      operationId: getSession
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Session info (user or null)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'

  /api/auth/sign-out:
    post:
      summary: Sign out current user
      description: Invalidate session and clear cookie
      operationId: signOut
      security:
        - cookieAuth: []
      responses:
        '200':
          description: Logout successful
          headers:
            Set-Cookie:
              schema:
                type: string
              description: Cleared session cookie
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: session_token

  schemas:
    SignUpRequest:
      type: object
      required:
        - email
        - password
        - programmingLevel
        - hardwareBackground
        - learningGoals
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          minLength: 8
          example: securepass123
        name:
          type: string
          example: John Doe
        programmingLevel:
          type: string
          enum: [beginner, intermediate, advanced]
          example: intermediate
        hardwareBackground:
          type: string
          enum: [none, hobbyist, professional]
          example: hobbyist
        learningGoals:
          type: array
          items:
            type: string
            enum: [career_transition, academic, personal, upskilling]
          minItems: 1
          example: [career_transition, upskilling]

    SignInRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          example: user@example.com
        password:
          type: string
          example: securepass123

    User:
      type: object
      properties:
        id:
          type: string
          format: uuid
        email:
          type: string
          format: email
        name:
          type: string
        programmingLevel:
          type: string
          enum: [beginner, intermediate, advanced]
        hardwareBackground:
          type: string
          enum: [none, hobbyist, professional]
        learningGoals:
          type: array
          items:
            type: string

    AuthResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        message:
          type: string
          example: Account created successfully

    SessionResponse:
      type: object
      properties:
        session:
          type: object
          nullable: true
          properties:
            user:
              $ref: '#/components/schemas/User'

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Invalid credentials
        detail:
          type: string
          example: Email or password is incorrect
